name: movie
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: 0.13.3
  carousel_slider: 4.0.0
  shared_preferences: 2.0.7
  provider: 6.0.0
  firebase_auth: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

msix_config:
  display_name: Movie
  publisher_display_name: David Miguel
  identity_name: company.epn.movie
  msix_version: 1.0.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
