// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13BurKEjHQqzpYsD0-V07a8RNKBgWsEI',
    appId: '1:921945470639:web:a86c0fd62be8f89839065a',
    messagingSenderId: '921945470639',
    projectId: 'fir-flutter-codelab-b5aab',
    authDomain: 'fir-flutter-codelab-b5aab.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b5aab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqEkzOvQK0dwoT0an_j0eHPyb3nIF_rNQ',
    appId: '1:921945470639:android:1e5a3dcf8f43134539065a',
    messagingSenderId: '921945470639',
    projectId: 'fir-flutter-codelab-b5aab',
    storageBucket: 'fir-flutter-codelab-b5aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VoE1Ga9zUmIUyEOZ72QCYX7_5rgEbtE',
    appId: '1:921945470639:ios:e194e8463e79f48439065a',
    messagingSenderId: '921945470639',
    projectId: 'fir-flutter-codelab-b5aab',
    storageBucket: 'fir-flutter-codelab-b5aab.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_VoE1Ga9zUmIUyEOZ72QCYX7_5rgEbtE',
    appId: '1:921945470639:ios:6611d6a77ec40d9939065a',
    messagingSenderId: '921945470639',
    projectId: 'fir-flutter-codelab-b5aab',
    storageBucket: 'fir-flutter-codelab-b5aab.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC13BurKEjHQqzpYsD0-V07a8RNKBgWsEI',
    appId: '1:921945470639:web:a86c0fd62be8f89839065a',
    messagingSenderId: '921945470639',
    projectId: 'fir-flutter-codelab-b5aab',
    authDomain: 'fir-flutter-codelab-b5aab.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b5aab.appspot.com',
  );
}
